name: Build Flutter APK from ZIP
on: [push]
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: Extract Project ZIP
         run: |
           unzip card_wars.zip -d extracted_project
           cd extracted_project/*
           mv * ../
           cd ..
       - uses: subosito/flutter-action@v2
         with:
           flutter-version: '3.x'
           channel: 'stable'
       - run: flutter pub get
       - run: flutter build apk --release
       - uses: actions/upload-artifact@v4
         with:
           name: app-release
           path: build/app/outputs/flutter-apk/app-release.apk
